package models

import (
	"superapps/entities"
)

type CourierPricingResponse entities.CourierPricingResponse
type Courier entities.Courier
type CourierData entities.Courier
type CourierRate entities.CourierRate
type CreateLocation entities.CreateLocation
type CreateLocationResponse entities.CreateLocationResponse
type RateByCoordinate entities.RateByCoordinate
type RateByCoordinateResponse entities.RateByCoordinateResponse
type OrderByCoordinate entities.OrderByCoordinate
type OrderInfo entities.OrderInfo
type OrderInfoResponse entities.OrderInfoResponse
type OrderByCoordinateResponse entities.OrderByCoordinateResponse
type GetTracking entities.GetTracking
type Tracking entities.Tracking